# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 26))
        self.menubar.setObjectName("menubar")
        self.menuInputData = QtWidgets.QMenu(self.menubar)
        self.menuInputData.setObjectName("menuInputData")
        self.menuClean_Data = QtWidgets.QMenu(self.menubar)
        self.menuClean_Data.setObjectName("menuClean_Data")
        self.menuAnalyze_Data = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze_Data.setObjectName("menuAnalyze_Data")
        self.menuVisualize_Data = QtWidgets.QMenu(self.menubar)
        self.menuVisualize_Data.setObjectName("menuVisualize_Data")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWEB_API = QtWidgets.QAction(MainWindow)
        self.actionWEB_API.setObjectName("actionWEB_API")
        self.actionWEB_SELENIUM = QtWidgets.QAction(MainWindow)
        self.actionWEB_SELENIUM.setObjectName("actionWEB_SELENIUM")
        self.actionCSV_FILE = QtWidgets.QAction(MainWindow)
        self.actionCSV_FILE.setObjectName("actionCSV_FILE")
        self.actionPANDAS = QtWidgets.QAction(MainWindow)
        self.actionPANDAS.setObjectName("actionPANDAS")
        self.actionPANDAS_2 = QtWidgets.QAction(MainWindow)
        self.actionPANDAS_2.setObjectName("actionPANDAS_2")
        self.actionMATPLOTLIB = QtWidgets.QAction(MainWindow)
        self.actionMATPLOTLIB.setObjectName("actionMATPLOTLIB")
        self.actionBOKEH = QtWidgets.QAction(MainWindow)
        self.actionBOKEH.setObjectName("actionBOKEH")
        self.menuInputData.addAction(self.actionWEB_API)
        self.menuInputData.addAction(self.actionWEB_SELENIUM)
        self.menuInputData.addAction(self.actionCSV_FILE)
        self.menuClean_Data.addAction(self.actionPANDAS)
        self.menuAnalyze_Data.addAction(self.actionPANDAS_2)
        self.menuVisualize_Data.addAction(self.actionMATPLOTLIB)
        self.menuVisualize_Data.addAction(self.actionBOKEH)
        self.menubar.addAction(self.menuInputData.menuAction())
        self.menubar.addAction(self.menuClean_Data.menuAction())
        self.menubar.addAction(self.menuAnalyze_Data.menuAction())
        self.menubar.addAction(self.menuVisualize_Data.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuInputData.setTitle(_translate("MainWindow", "Get Data"))
        self.menuClean_Data.setTitle(_translate("MainWindow", "Clean Data"))
        self.menuAnalyze_Data.setTitle(_translate("MainWindow", "Analyze Data"))
        self.menuVisualize_Data.setTitle(_translate("MainWindow", "Visualize Data"))
        self.actionWEB_API.setText(_translate("MainWindow", "WEB API"))
        self.actionWEB_SELENIUM.setText(_translate("MainWindow", "WEB SELENIUM"))
        self.actionCSV_FILE.setText(_translate("MainWindow", "CSV FILE"))
        self.actionPANDAS.setText(_translate("MainWindow", "PANDAS "))
        self.actionPANDAS_2.setText(_translate("MainWindow", "PANDAS"))
        self.actionMATPLOTLIB.setText(_translate("MainWindow", "MATPLOTLIB"))
        self.actionBOKEH.setText(_translate("MainWindow", "BOKEH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
