# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'username_taken.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Username_taken(object):
    def setupUi(self, Username_taken):
        Username_taken.setObjectName("Username_taken")
        Username_taken.resize(708, 187)
        self.label = QtWidgets.QLabel(Username_taken)
        self.label.setGeometry(QtCore.QRect(40, 70, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 0, 0)")
        self.label.setObjectName("label")

        self.retranslateUi(Username_taken)
        QtCore.QMetaObject.connectSlotsByName(Username_taken)

    def retranslateUi(self, Username_taken):
        _translate = QtCore.QCoreApplication.translate
        Username_taken.setWindowTitle(_translate("Username_taken", "Dialog"))
        self.label.setText(_translate("Username_taken", "Username already in use, please choose another one!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Username_taken = QtWidgets.QDialog()
    ui = Ui_Username_taken()
    ui.setupUi(Username_taken)
    Username_taken.show()
    sys.exit(app.exec_())
